# Generated by Django 3.2.7 on 2021-09-09 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='typeUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.typeuser'),
        ),
    ]
